Repository dokc/rebuilding-explorers-world, pull requests merged in 2022-10, with the labels that each got.

#15 Add greeting messages
  .github/workflows/greetings.yml
Labels: good first issue, help wanted, hacktoberfest

#16 Addition of Navbar Component
  package-lock.json
  src/components/navbar.astro
  src/images/download.png
  src/pages/index.astro
  src/stylesheets/navbar.css
  yarn.lock
Labels: enhancement, good first issue, hacktoberfest

#9 Added Issue Templates
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
Labels: enhancement, good first issue, help wanted, hacktoberfest
